import '~/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

import { TRPCReactProvider } from '~/trpc/client';
import { HydrateClient } from '~/trpc/server';
import { SessionProvider } from 'next-auth/react';

import { SidebarProvider } from '~/components/ui/sidebar';
import { NextThemeProvider } from '~/components/context/theme';

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
    <html lang='en' className={`${GeistSans.variable}`} suppressHydrationWarning>
        <body className='hidden sm:block'>
            <TRPCReactProvider>
                <HydrateClient>
                    <NextThemeProvider>
                        <SessionProvider>
                            <SidebarProvider>{children}</SidebarProvider>
                        </SessionProvider>
                    </NextThemeProvider>
                </HydrateClient>
            </TRPCReactProvider>
        </body>
    </html>
);

export default RootLayout;
